#!/bin/bash
# aja järgi tervitus

kasutajanimi=$(whoami)

tund=$(date +"%H")

echo -n "Sisesta aja väärtus: "
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
    echo "Tere hommikust, $kasutajanimi!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
    echo "Tere päevast, $kasutajnimi!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
    echo "Tere õhtust, $kasutajanimi!"
elif [ $aeg -ge 22 -o $aeg -lt 6 ]; then
    echo "Head ööd, $kasutajanimi!"
else
    echo "Vigane aja väärtus"
fi

