#!/bin/bash
# aja järgi tervitus

echo -n "Sisesta aja väärtus: "
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
    echo "Tere hommikust"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
    echo "Tere päevast"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
    echo "Tere õhtust"
elif [ $aeg -ge 22 -o $aeg -lt 6 ]; then
    echo "Head ööd!"
else
    echo "Vigane aja väärtus"
fi

