#!/bin/bash
# aja järgi tervitus

kasutajanimi=$(whoami)

kasutajanimi_suur=$(echo $kasutajanimi | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}')

tund=$(date +"%H")

if [ $tund -ge 6 -a $tund -lt 12 ]; then
    echo "Tere hommikust, $kasutajanimi_suur!"
elif [ $tund -ge 12 -a $tund -lt 18 ]; then
    echo "Tere päevast, $kasutajanimi_suur!"
elif [ $tund -ge 18 -a $tund -lt 22 ]; then
    echo "Tere õhtust, $kasutajanimi_suur!"
elif [ $tund -ge 22 -o $tund -lt 6 ]; then
    echo "Head ööd, $kasutajanimi_suur!"
else
    echo "Midagi läks valesti"
fi

